# Generated by Django 5.0.1 on 2024-02-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Image', models.ImageField(upload_to='images')),
                ('Description', models.CharField(max_length=20)),
            ],
        ),
    ]
