# Generated by Django 5.0.1 on 2024-02-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Image', models.ImageField(upload_to='images')),
                ('Price', models.IntegerField()),
                ('Quantity', models.CharField(max_length=10)),
            ],
        ),
    ]
