# Generated by Django 5.0.1 on 2024-03-01 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_checkoutdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='checkoutdata',
            new_name='Checkout',
        ),
    ]
